version: '3.1'
services:
  memsql-studio:
    image: katoni/memsql-studio:latest
    build: .
    ports:
      - 8080:8080
    volumes:
      - memsql-studio-data:/var/lib/memsql-studio/

volumes:
  memsql-studio-data: